server:
  port: 8082

spring:
  application:
    name: assessment-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/securecode_assessment?TimeZone=UTC
    username: securecode
    password: securecode
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
